### ISSUE TITLE
Could you please add https://steam-repacks.com/ and https://worldof-pcgames.net/

### ISSUE THREAD

**Issue by ZulqarnainKaan** [streambase-project/streambase#197]
Greetings dear mods, great work on the mega thread, could you please add my sites 

https://steam-repacks.com/ and https://worldof-pcgames.net/

**Comment by streambase-project** [comment]
@ZulqarnainKaan for now, we only add “unique” sites from this category, because many of these sites have very similar, if not identical, files. So, I have to refuse for now.

**Comment by ZulqarnainKaan** [comment]
Thank you dear mod for looking into my sites, Please let me explain why they should be added and why are they unique.

Firstly, all of our games are updated to their latest versions.
The games are pre-installed, fixed all errors applied patches, so users just need to extract and play the game
We have an awesome discord community, where we help with any kind of game errors

And we provide the best download speeds for free to all our users, its something that i promise you no other website provides.
We also make sure to provide only official releases of the game.

Hopefully you will reconsider our website.

**Comment by streambase-project** [comment]
@streambase-project we mean that the files/games you offer are already on one of the pages in our section. The only argument for adding your sites is full download speed.

And this argument is not that important, because many files are placed on torrents where the speed is on the side of the downloader, and on warez sites, links hosting files can be generated via debrids, and then full download speeds are also obtained.

**Comment by streambase-project** [comment]
@ZulqarnainKaan we mean that the files/games you offer are already on one of the pages in our section. The only argument for adding your sites is full download speed.

And this argument is not that important, because many files are placed on torrents where the speed is on the side of the downloader, and on warez sites, links hosting files can be generated via debrids, and then full download speeds are also obtained.

For now, the decision remains unchanged, unless someone also expresses support for adding this sites.
